cerita7app/urls.py
from django.urls import path
from .views import home

app_name = 'cerita7app'

urlpatterns = [
	path('', home, name='home'),
	]

cerita8app/urls.py
from django.urls import path
from .views import bookPage

app_name = 'cerita8app'

urlpatterns = [
	path('', bookPage, name='bookPage'),
	]

cerita9app/urls.py
from django.urls import path
from .views import landingPage, loginView, logoutView


app_name = 'cerita9app'

urlpatterns = [
	path('', landingPage, name='landingPage'),
    path('login/', loginView, name='login' ),
    path('logout/', logoutView, name='logout'),

	]

story7/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('cerita7app.urls')),
    path('cerita8/', include('cerita8app.urls')),
    path('cerita9/', include('cerita9app.urls')),
]

cerita7app/models.py
from django.db import models

# Create your models here.

cerita8app/models.py
from django.db import models

# Create your models here.

cerita9app/models.py
from django.db import models

# Create your models here.

cerita7app/views.py
from django.shortcuts import render

# Create your views here.
def home(request):
    response = {}
    return render(request, 'home.html', response)

cerita8app/views.py
from django.shortcuts import render

# Create your views here.
def bookPage(request):
    response = {}
    return render(request, 'bookPage.html', response)

cerita9app/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User

# Create your views here.
def landingPage(request):
    context = { 
        'greeting' : 'Welcome',
        'please' : 'Do you have an account?',
        'log' : 'login',
    }
    
    if request.user.is_authenticated:
        context['greeting'] = 'Welcomeback ' + request.session["username"]
        context['please'] = 'Please Log Out'
        context['log'] = 'logout'

    return render(request, 'landingPage.html', context)


def loginView(request):
    if request.method == "GET":
        if request.user.is_authenticated:
            return redirect('/cerita9/')
        else:
            return render(request, 'login.html')

    if request.method == "POST":
        if len(request.POST) == 3:
            username_login = request.POST['username']
            password_login = request.POST['password']
                    
            user = authenticate(request, username=username_login, password=password_login)
            
            if user is not None:
                login(request, user)
                request.session['username'] = user.username
                return redirect('/cerita9/')
            else:
                return redirect('login')
        elif len(request.POST) == 4:
            username_login = request.POST['username']
            email_login = request.POST['email']
            password_login = request.POST['password']

            users = User.objects.all()

            for user in users:
                if user.username == username_login :
                    return redirect('login')

            user = User.objects.create_user(username=username_login, email=email_login, password=password_login)
            login(request, user)
            request.session["username"] = user.username
            return redirect('/cerita9/')

 
@login_required
def logoutView(request):
    request.session.flush()
    if request.method == "GET":
        if request.user.is_authenticated:
            logout(request)
    return redirect('/cerita9/')

cerita7app/templates/home.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.2/css/bootstrap.min.css" integrity="sha384-Smlep5jCw/wG7hdkwQ/Z5nLIefveQRIY9nfy6xoR1uRYBtpZgI6339F5dgvm/e9B" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Oswald&display=swap">
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha256-pasqAKBDmFT4eHoN2ndd6lN370kFiGUFyTiUHWhU7k8=" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>

    <link rel="stylesheet" type="text/css" href= "{% static 'home.css' %}">




    <title>{{ Hello }}</title>
</head>
<body>
<div class="content">
    <div class="desc-section">
            <div class="container">
                <div class="row">
                    <div class="dropdown margin-tb-30">
                                <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenu2" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    Change Theme
                                </button>
                                <div class="dropdown-menu" aria-labelledby="dropdownMenu2">
                                    <button class="dropdown-item" type="button" id="changeLight">Light</button>
                                    <button class="dropdown-item" type="button" id="changeDark">Dark</button>
                                </div>
                            </div>
                </div>
                <div class="row">
                    <div class="col-sm-4"> </div>
                    <div class="col-sm-4">
                        <div class="desc">
                            <div class="profile-img"><img src="{% static 'bela.jpg' %}" alt=""></div>
                            <h3>Sinta Bela Damayanti</h3>
                            <p> 1806147193 <p>
                            <br>     
                    </div>
        
                    
                            
                            <ul class="accordion">
                                <li>
                                    <a class="toggle" href="javascript:void(0);" id="act">Kegiatan</a>
                                    <ul class="inner" id="activities">
                                    <li>Belajar</li>
                                    <li>Ngerjain Tugas PPW</li>
                                    <li>Ngerjain Tugas SDA</li>
                                    <li>Ngerjain Tugas ADBIS</li>
                                    <li>Ngerjain Tugas PPM</li>
                                    <li>Rapat Betis</li>
                                    <li>Sholat 5 waktu</li>
                                    </ul>
                                </li>

                                <li>
                                    <a class="toggle" href="javascript:void(0);" id="org">Pengalaman Organisasi</a>
                                    <ul class="inner" id="organization">
                                        <li>PJ Acara Betis</li>
                                        <li>HRD of Direct Marketing Compfest</li>
                                        <li>Staff Acara CGT</li>
                                        <li>Staff Acara Betis</li>
                                        <li>Staff Dokum Universiade UI</li>
                                    </ul>
                                </li>

                                <li>
                                    <a class="toggle" href="javascript:void(0);" id="ach"> Prestasi</a>
                                    <ul class="inner" id="achievement">
                                    <li>otw</li>
                                    <li>yah</li>
                                    <li>doain</li>
                                    <li>aja</li>
                                </ul>
                                </li>
                            </ul>
                        </div>  
                        </div>
                    
                </div>
           </div>
        </div>
        </div>

    <script type="text/javascript" src="{% static 'home.js' %}"></script>
    
</body>
</html>

cerita8app/templates/bookPage.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>

<meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.2/css/bootstrap.min.css" integrity="sha384-Smlep5jCw/wG7hdkwQ/Z5nLIefveQRIY9nfy6xoR1uRYBtpZgI6339F5dgvm/e9B" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Oswald&display=swap">
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha256-pasqAKBDmFT4eHoN2ndd6lN370kFiGUFyTiUHWhU7k8=" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>

    <link rel="stylesheet" type="text/css" href= "{% static 'bookPage.css' %}">




  <title>Sinta Bela Damayanti</title>


</head>

<body>
<div class="jumbotron-fluid">
    <div class="jumbotron justify-content-center">
          <br>
          <h3>Search your favorite books here!</h3>
          <br>
          <div class="form-inline active-grey-4 search">
                <input class="form-control form-control-sm mr-3 w-100 text-align-center" id="search" type="text" placeholder="Search" autocomplete="off">
               
          </div>
          
              <table class="table" id="myTable">
    </table>











    </div>
</div>

<script type="text/javascript" src="{% static 'bookPage.js' %}"></script>

</body>
</html>

cerita9app/templates/landingPage.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>

<meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.2/css/bootstrap.min.css" integrity="sha384-Smlep5jCw/wG7hdkwQ/Z5nLIefveQRIY9nfy6xoR1uRYBtpZgI6339F5dgvm/e9B" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Oswald&display=swap">
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha256-pasqAKBDmFT4eHoN2ndd6lN370kFiGUFyTiUHWhU7k8=" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <link rel="stylesheet" type="text/css" href= "{% static 'cerita9.css' %}">





  <title>Sinta Bela Damayanti</title>


</head>

<body>

<div class="form">
		<h1>{{greeting}}<br>{{please}}</h1>
		{% if log == "login" %}
		<button type="button" id="login" class="button button-block" onclick="window.location.href='{% url 'cerita9app:login' %}'">Log In / Sign Up</button>
		{% elif log == "logout" %}
		<button type="button" id="logout" class="button button-block" onclick="window.location.href='{% url 'cerita9app:logout' %}'">Log Out</button>
		{% endif %}
	</div>


<script type="text/javascript" src="{% static 'cerita9.js' %}"></script>
</body>
</html>

cerita9app/templates/login.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>

<meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.2/css/bootstrap.min.css" integrity="sha384-Smlep5jCw/wG7hdkwQ/Z5nLIefveQRIY9nfy6xoR1uRYBtpZgI6339F5dgvm/e9B" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Oswald&display=swap">
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha256-pasqAKBDmFT4eHoN2ndd6lN370kFiGUFyTiUHWhU7k8=" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <link rel="stylesheet" type="text/css" href= "{% static 'cerita9.css' %}">





  <title>Sinta Bela Damayanti</title>


</head>

<body>

<div class="form">
		<ul class="tab-group">
			<li class="tab active"><a id="title_login" href="#login">Log In</a></li>
			<li class="tab "><a id="title_signup" href="#signup">Sign Up</a></li>
			
		</ul>
		
		<div class="tab-content">
			<div id="login">   
				<h1>Hello</h1>
			
				<form method="POST">
					{% csrf_token %}
				
					<div class="field-wrap">
						<label>
						Username<span class="req">*</span>
						</label>
						<input type="text" name="username" id="username_login" required autocomplete="off"/>
					</div>
				
					<div class="field-wrap">
						<label>
						Password<span class="req">*</span>
						</label>
						<input type="password" name="password" id="password_login" required autocomplete="off"/>
					</div>
				
					<button type="submit" id="submit_login" class="button button-block">Log In</button>
				
				</form>
	
			</div>

			<div id="signup">   
				<h1>Sign Up Here</h1>
				
				<form method="POST">
					{% csrf_token %}
					<div class="field-wrap">
						<label>
							Username<span class="req">*</span>
						</label>
						<input type="text" name="username" id="username_signup" required autocomplete="off" />
					</div>
					
					<div class="field-wrap">
						<label>
						Email Address<span class="req">*</span>
						</label>
						<input type="email" name="email" id="email_signup" required autocomplete="off"/>
					</div>
					
					<div class="field-wrap">
						<label>
						Set A Password<span class="req">*</span>
						</label>
						<input type="password" name="password" id="password_signup" required autocomplete="off"/>
					</div>
					
					<button type="submit" id="submit_signup" class="button button-block">SIGN UP</button>
					
				</form>
	
			</div>
			
		</div><!-- tab-content -->
		
	</div> <!-- /form -->

<script type="text/javascript" src="{% static 'cerita9.js' %}"></script>
</body>
</html>